FROM php:8.4-cli-alpine
WORKDIR /opt/laravel

RUN apk --no-cache add icu-dev icu-libs libzip-dev \
    && docker-php-ext-install pdo pdo_mysql intl zip

COPY --from=composer/composer:latest-bin /composer /usr/bin/composer

COPY composer.json composer.lock ./
RUN composer install --no-interaction --no-scripts --optimize-autoloader

COPY . .

RUN php artisan config:clear

CMD ["sh", "-c", "php artisan migrate --force && php artisan test"]
