name: Feature Request
description: A new feature or change to existing functionality.
title: "✨ "
projects: ["aula-app/1"]
type: "Feature"
body:
  - type: markdown
    attributes:
      value: "## ✨ Feature Request"
  - type: textarea
    id: description-feature
    attributes:
      label: Details
      description: Describe the feature that is being requested.
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: A set of assumptions which, when tested, verify that the feature was implemented.
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
  - type: markdown
    attributes:
      value: |
        ### 🚢 Definition of Ready
        Ensure the issue meets the criteria in our [Definition of Ready](https://github.com/aula-app/team-handbook/handbook/definition-of-ready-and-done.md) before it can be accepted for development.
