networks:
  aula_local:
    driver: bridge
    external: true

services:
  aula-backend-legacy:
    build:
      context: ./
    environment:
      APACHE_SERVER_NAME: localhost
      APP_ENV: local
    ports:
      - "8080:80"
    volumes:
      - ./docker-local/_generated_files_data:/var/www/html/files:rw
      - type: bind
        source: ./src
        target: /var/www/html/api
        bind:
          create_host_path: false
      - type: bind
        source: ./config/
        target: /var/www/html/config
        bind:
          create_host_path: false
      - type: bind
        source: ./docker-local/php.ini-development
        target: /etc/php/8.3/apache2/php.ini
        bind:
          create_host_path: true
    networks:
      - aula_local
