name: Update test backend

on: 
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: self-hosted
    env:
      CI: true
      LOCAL: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Copy files
        run: |
          cp -vr * /var/www-aula-dev/api
          echo "Instances backend updated"
          # /home/actions-runner/recreate_db.sh
          # echo "Database recreated"
        shell: bash
