name: copy files 

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    env:
      CI: true
      LOCAL: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Copy files
        run: |
          cp -vr * /var/www/api
          cp -vr * /var/www-aula-test/api
          cp -vr * /var/www-aula-bw/api
          /home/actions-runner/recreate_db.sh
          echo "Database recreated"
        shell: bash

