name: scp copy files to remote development server

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      LOCAL: test
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_HOST_KEY" > ../private.key
          sudo chmod 600 ../private.key
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_HOST_KEY: ${{secrets.SSH_HOST_KEY}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - name: Copy folder content recursively to remote
        run: |
          ls -l $SSH_KEY_PATH
          scp -P 4222 ${{ github.workspace }} -i $SSH_KEY_PATH aula@devel.aula.de:
        env:
          SSH_HOST_KEY: ${{secrets.SSH_HOST_KEY}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key

