name: copy files 

on: 
  push

jobs:
  build:
    runs-on: self-hosted
    env:
      CI: true
      LOCAL: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create SSH key and copy files
        run: |
          ls -l 
        shell: bash

