name: copy files 

on: 
  push

jobs:
  build:
    runs-on: self-hosted
    env:
      CI: true
      LOCAL: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Copy files
        run: |
          cp -vr * /var/www/api
        shell: bash

