name: Update staging backend

on: 
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: self-hosted
    env:
      CI: true
      LOCAL: test
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Copy files
        run: |
          cp -vr * /var/www-aula-staging/api
          echo "Instances backend updated"
          # /home/actions-runner/recreate_staging_db.sh
          # echo "Database recreated"
        shell: bash

